ChatProject/ChatProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import  settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chatapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QC_BLOG/urls.py
from django.contrib import admin
from django.urls import path, include , re_path 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

urlpatterns += [
    re_path(r'^acounts/' , include('django.contrib.auth.urls')),
]

posts/urls.py
from django.conf.urls import re_path , url 
from . import views 
app_name = 'posts'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^posts/$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^writers/$', views.WriterListView.as_view(), name='writers'),
    url(r'^profile/$', views.User_profile_view, name='profile'),
]

posts/models.py
from django.db import models 
import uuid 
from django.shortcuts import reverse
class Post(models.Model):
    writer     = models.ForeignKey('Writer', on_delete = models.CASCADE)
    title      = models.CharField(max_length=150)
    body       = models.TextField()
    timestamp  = models.DateTimeField()
    assortment = models.ManyToManyField('Assortment', help_text ='please enter a assortment' )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:post_detail", kwargs={"pk": self.id})
    

class Writer(models.Model):
    first_name = models.CharField(max_length=20)
    last_name  = models.CharField(max_length = 25)
    birthDay   = models.DateField()

    def __str__(self):
        return self.first_name + self.last_name

    
class Assortment(models.Model):
    name = models.CharField(max_length = 20 , help_text = 'select a assortment for the your post')

    def __str__(self):
        return self.name


class User_profile(models.Model):
    user_name = models.CharField(max_length = 20)
    user_first_name = models.CharField(max_length = 20)
    user_last_name = models.CharField(max_length = 20)
    

posts/views.py
from django.shortcuts import render 
from . import models
from django.views import generic
from django.shortcuts import render
class Index(generic.TemplateView):
    template_name = 'index.html'

    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = models.Post.objects.all().count()
        context['authors'] = models.Writer.objects.all().count()

        return context



class PostListView(generic.ListView):
    model = models.Post
    template_name = 'post_list.html'
    

class WriterListView(generic.ListView):
    model         = models.Writer
    template_name = 'writer_list.html'


class PostDetailView(generic.DetailView):
    model = models.Post
    template_name = 'post_detail.html'

def User_profile_view(request):
    user_name = models.User_profile.user_name
    firstname = models.User_profile.user_first_name
    lastname  = models.User_profile.user_last_name

    return render(request , '../templates/registration/profile.html' ,{'user_name':user_name , 'firstname':firstname , 'lastname':lastname})

posts/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>weblog posts</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'style.css' %}"> 
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav" style = "border-right: 1px solid #aaa">
          <li style = "padding:10px 0 ; font-size:17px"><a href="{% url 'posts:index' %}">Home</a></li>
          <li style = "padding:10px 0; font-size:17px"><a href="{% url 'posts:post_list'%}">All posts</a></li>
          <li style = "padding:10px 0; font-size:17px"><a href="{% url 'posts:writers' %}">All authors</a></li>
          <li style = "padding:10px 0; font-size:17px"><a href='/admin/'>Admin Page </a> </li>
          {% if user.is_authenticated %}
            <li>User : {{user.get_username }} </li>
            <li><a href="{% url 'logout' %} next={{request.path}}" > Log out</a></li>
          {% else %}
            <li><a href="{% url 'login' %} next={{request.path}}" > Login</a></li>
          {% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>

posts/templates/index.html
{% extends "base_template.html" %}

{% block content %}
<h1>QC webiste</h1>

  <p>Welcome to <em>QC website</em>, a very basic Django website </p>

<h2>Dynamic content</h2>

  <p>The webiste has the following record counts:</p>
  <ul>
    <li><strong> <a href="{% url 'posts:post_list' %}">posts:</a></strong> {{ posts }}</li>
    <li><strong><a href=''>writers:</a></strong> {{ authors }}</li>
  </ul>

{% endblock %}

posts/templates/post_detail.html
{% extends "base_template.html" %}

{% block content %}
  <h1>Title: {{ post.title }}</h1>

  <p><strong>writer:</strong> <a href="">{{ post.writer }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>title:</strong> {{ post.title }}</p>
  <p><strong>body:</strong> {{ post.body }}</p> 
  <p><strong>time:</strong> {{ post.timestamp }}</p>  
  <p><strong>assortment:</strong> {% for genre in post.assortment.all %} {{ assortment }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  


{% endblock %}

posts/templates/post_list.html
{% extends "base_template.html" %}

{% block content %}


    <h1>Post List</h1>
      {% for post in post_list %}
        <h3>
        <a href="{{post.get_absolute_url}}">{{post.title}} </a></h3> 
        <p> <strong>نویسنده : </strong>{{post.writer}} </p>
        <p> <strong>تاریخ انتشار :</strong> {{post.timestamp}} </p>
        <hr/>
      {% endfor %}
    </ul>
       
{% endblock %}

posts/templates/writer_list.html
{% extends "base_template.html" %}

{% block content %}


    <h1>Writers List</h1>

    <ul>

      {% for writer in writer_list %}
        <div >
            <h3>نویسنده  :<a href=""> {{ writer.last_name}} </a></h3>
            <p>نام : {{ writer.first_name}} </p>
            <p>تاریخ تولد : {{writer.birthDay}}   </p>
            <hr />
        </div>
      {% endfor %}

    </ul>
       
{% endblock %}